//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobGroup
    {
        public JobGroup()
        {
            this.Client_JobGroup = new HashSet<Client_JobGroup>();
            this.Jobs = new HashSet<Job>();
        }
    
        public int JobGroupID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Status { get; set; }
        public int TaskGroupID { get; set; }
    
        public virtual ICollection<Client_JobGroup> Client_JobGroup { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual TaskGroup TaskGroup { get; set; }
    }
}
