//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_TaskGroup
    {
        public int TaskID { get; set; }
        public int TaskGroupID { get; set; }
        public int TaskOrder { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TaskGroup TaskGroup { get; set; }
    }
}
