USE [master]
GO

/****** Object:  Database [TestJobDB]    Script Date: 12/30/2013 21:50:32 ******/
CREATE DATABASE [TestJobDB] ON  PRIMARY 
( NAME = N'TestJobDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\TestJobDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestJobDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\TestJobDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TestJobDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestJobDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestJobDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestJobDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestJobDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestJobDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestJobDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestJobDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestJobDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TestJobDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestJobDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestJobDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestJobDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestJobDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestJobDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestJobDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestJobDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestJobDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestJobDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestJobDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestJobDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestJobDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestJobDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestJobDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestJobDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestJobDB] SET  READ_WRITE 
GO

ALTER DATABASE [TestJobDB] SET RECOVERY FULL 
GO

ALTER DATABASE [TestJobDB] SET  MULTI_USER 
GO

ALTER DATABASE [TestJobDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestJobDB] SET DB_CHAINING OFF 
GO


