//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTechnology.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMachineInfo
    {
        public ClientMachineInfo()
        {
            this.Client_JobGroup = new HashSet<Client_JobGroup>();
        }
    
        public string ClientID { get; set; }
        public string OS { get; set; }
        public string SystemType { get; set; }
        public string MachineName { get; set; }
    
        public virtual ICollection<Client_JobGroup> Client_JobGroup { get; set; }
    }
}
